# Generated by Django 4.2.9 on 2025-04-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hremployee',
            old_name='department',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='hremployee',
            name='designation',
        ),
        migrations.AddField(
            model_name='hremployee',
            name='email',
            field=models.EmailField(default='hi@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hremployee',
            name='phone',
            field=models.CharField(default='hello@gmail.com', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HRSalarySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_management.hremployee')),
            ],
        ),
    ]
