filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]