# Generated by Django 4.2.9 on 2025-04-16 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('it_management', '0003_remove_sessionlog_activity_summary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagedUser',
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
