# Generated by Django 4.2.9 on 2025-04-16 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pam_hris', '0002_sessionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='sessionlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
