# Generated by Django 4.2.9 on 2025-04-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pam_hris', '0003_remove_sessionlog_action_remove_sessionlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
